services:
  backend:
    build: backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development

  frontend:
    build: frontend
    container_name: frontend
    ports:
      - "8081:80"